---
apiVersion: v1
kind: Service
metadata:
  name: valheim-udp
  namespace: valheim
spec:
  type: LoadBalancer
  selector:
    app: valheim-dep
  ports:
    - name: valheim-udp1
      port: 2456
      targetPort: 2456
      protocol: UDP
    - name: valheim-udp1
      port: 2457
      targetPort: 2457
      protocol: UDP
